version: "3"
volumes:
  opensearch: {}
  data: {}

services:
  # OpenSearch should only be used when testing / development where no external opensearch service is available.
  opensearch:
    image: opensearchproject/opensearch:1
    environment:
      DISABLE_INSTALL_DEMO_CONFIG: ${DISABLE_INSTALL_DEMO_CONFIG}
      DISABLE_SECURITY_PLUGIN: ${DISABLE_SECURITY_PLUGIN}
      OPENSEARCH_JAVA_OPTS: ${OPENSEARCH_JAVA_OPTS}
      bootstrap.memory_lock: ${BOOTSTRAP_MEMORY_LOCK}
      discovery.type: ${DISCOVERY_TYPE}
    volumes:
      - opensearch:/usr/share/opensearch/data

  opencast-admin:
    image: lp-opencast-admin:12.2
    environment:
      ELASTICSEARCH_SERVER_HOST: ${ELASTICSEARCH_SERVER_HOST}
      ORG_OPENCASTPROJECT_DB_JDBC_PASS: ${ORG_OPENCASTPROJECT_DB_JDBC_PASS}
      ORG_OPENCASTPROJECT_DB_JDBC_URL: ${ORG_OPENCASTPROJECT_DB_JDBC_URL}
      ORG_OPENCASTPROJECT_DB_JDBC_USER: ${ORG_OPENCASTPROJECT_DB_JDBC_USER}
      ORG_OPENCASTPROJECT_DB_VENDOR: ${ORG_OPENCASTPROJECT_DB_VENDOR}
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: ${ORG_OPENCASTPROJECT_DOWNLOAD_URL}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER}
      ORG_OPENCASTPROJECT_SERVER_URL: ${ORG_OPENCASTPROJECT_SERVER_URL_ADMIN}
      PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL}
      PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL}
    ports:
      - "8080:8080"
    volumes:
      - data:/data

  opencast-presentation:
    image: lp-opencast-presentation:12.2
    environment:
      ELASTICSEARCH_SERVER_HOST: ${ELASTICSEARCH_SERVER_HOST}
      ORG_OPENCASTPROJECT_DB_JDBC_PASS: ${ORG_OPENCASTPROJECT_DB_JDBC_PASS}
      ORG_OPENCASTPROJECT_DB_JDBC_URL: ${ORG_OPENCASTPROJECT_DB_JDBC_URL}
      ORG_OPENCASTPROJECT_DB_JDBC_USER: ${ORG_OPENCASTPROJECT_DB_JDBC_USER}
      ORG_OPENCASTPROJECT_DB_VENDOR: ${ORG_OPENCASTPROJECT_DB_VENDOR}
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: ${ORG_OPENCASTPROJECT_DOWNLOAD_URL}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER}
      ORG_OPENCASTPROJECT_SERVER_URL: ${ORG_OPENCASTPROJECT_SERVER_URL_PRESENTATION}
      PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL}
      PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL}
    ports:
      - "8081:8080"
    volumes:
      - data:/data

  opencast-worker-1:
    image: lp-opencast-worker:12.2
    environment:
      ELASTICSEARCH_SERVER_HOST: ${ELASTICSEARCH_SERVER_HOST}
      ORG_OPENCASTPROJECT_DB_JDBC_PASS: ${ORG_OPENCASTPROJECT_DB_JDBC_PASS}
      ORG_OPENCASTPROJECT_DB_JDBC_URL: ${ORG_OPENCASTPROJECT_DB_JDBC_URL}
      ORG_OPENCASTPROJECT_DB_JDBC_USER: ${ORG_OPENCASTPROJECT_DB_JDBC_USER}
      ORG_OPENCASTPROJECT_DB_VENDOR: ${ORG_OPENCASTPROJECT_DB_VENDOR}
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: ${ORG_OPENCASTPROJECT_DOWNLOAD_URL}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER}
      ORG_OPENCASTPROJECT_SERVER_URL: ${ORG_OPENCASTPROJECT_SERVER_URL_WORKER_1}
      PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL}
      PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL}
    volumes:
      - data:/data
