version: "3"

volumes:
  data:
    external: true

services:
  opencast-worker-1:
    image: cspcappdevcr.azurecr.io/${CONTAINER_REPOSITORY_ROOT_NAME}/worker:${CONTAINER_REPOSITORY_TAG}
    environment:
      ORG_OPENCASTPROJECT_DB_JDBC_PASS: ${ORG_OPENCASTPROJECT_DB_JDBC_PASS}
      ORG_OPENCASTPROJECT_DB_JDBC_URL: ${ORG_OPENCASTPROJECT_DB_JDBC_URL}
      ORG_OPENCASTPROJECT_DB_JDBC_USER: ${ORG_OPENCASTPROJECT_DB_JDBC_USER}
      ORG_OPENCASTPROJECT_DB_VENDOR: ${ORG_OPENCASTPROJECT_DB_VENDOR}
      ORG_OPENCASTPROJECT_DOWNLOAD_URL: ${ORG_OPENCASTPROJECT_DOWNLOAD_URL}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS}
      ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER: ${ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS}
      ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER: ${ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER}
      ORG_OPENCASTPROJECT_SERVER_URL: ${PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL}
      PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL}
      PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL: ${PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL}
    volumes:
      - data:/data
