trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE

resources:
  repositories:
  - repository: lp-common
    type: git
    name: learning-platform/lp-common

variables:
- group: appDev-pb-public

pool:
  vmImage: ubuntu-20.04

steps:
- checkout: self # Multiple repos: files will be downloaded to ${Build.SourcesDirectory}/lp-opencast folder.
- checkout: lp-common # Multiple repos: files will be downloaded to ${Build.SourcesDirectory}/lp-common folder.

- task: Bash@3
  displayName: 'Set Build Repository Base Name Variable'
  env:
    BUILD_REPOSITORY_NAME: $(Build.Repository.Name)
    IS_OUTPUT: 'false'
    NAME: 'buildRepositoryBaseName'
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=${NAME};isOutput=${IS_OUTPUT}]$(basename ${BUILD_REPOSITORY_NAME})"

- template: templates/build-steps.yml
  parameters:
    buildNumber: $(Build.BuildNumber)
    buildSourceBranchName: $(Build.SourceBranchName)
    containerRegistryConnection: $(containerRegistryConnection)
    containerRepositoryBaseName: $(buildRepositoryBaseName)
