parameters:
- name: env
  type: string

resources:
  repositories:
  - repository: lp-common
    type: git
    name: learning-platform/lp-common

variables:
- group: lp-idm-global-clear
- ${{ if eq(parameters.env, 'dev') }}:
  - group: lp-common-dev-clear
  - group: lp-idm-dev-clear

jobs:
- deployment: TearDownResourcesJob
  displayName: 'Tear Down Environment Job'
  pool:
    vmImage: ubuntu-20.04
  environment: '$(resourceGroupName)'
  strategy:
      runOnce:
        deploy:
          steps:

          - checkout: lp-common # Single repos: files will be downloaded directly to ${Build.SourcesDirectory} folder.

          - task: Bash@3
            displayName: 'Set Resource Name Variables'
            inputs:
              filePath: 'azure/scripts/set_resource_name_variables_v2.sh'
              arguments: >-
                --component-name "$(componentName)"
                --environment-name "$(environmentName)"

          - task: AzureCLI@2
            displayName: 'Set App Service Slot Names Variable'
            inputs:
              azureSubscription: '$(serviceConnectionName)'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'azure/scripts/set_app_service_slot_names_variable_v2.sh'
              arguments: >-
                --app-service-name "$(appServiceName)"
                --resource-group-name "$(resourceGroupName)"
                --subscription-name "$(subscriptionName)"
                --variable-name "appServiceSlotNames"

          - task: AzureCLI@2
            displayName: 'Delete App Service Slots'
            # Condition: Run only when appServiceSlotNames is not an empty string.
            condition: variables['appServiceSlotNames']
            inputs:
              azureSubscription: '$(serviceConnectionName)'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'azure/scripts/delete_app_service_slots_v2.sh'
              arguments: >-
                --app-service-name "$(appServiceName)"
                --app-service-slot-names "$(appServiceSlotNames)"
                --resource-group-name "$(resourceGroupName)"
                --subscription-name "$(subscriptionName)"

          - task: AzureCLI@2
            displayName: 'Delete Component''s Resources'
            inputs:
              azureSubscription: '$(serviceConnectionName)'
              scriptType: 'bash'
              scriptLocation: 'scriptPath'
              scriptPath: 'azure/scripts/delete_component_resources_v2.sh'
              arguments: >-
                --app-service-name "$(appServiceName)"
                --app-service-plan-name "$(appServicePlanName)"
                --component-name "$(componentName)"
                --database-server-name "$(databaseServerName)"
                --log-analytics-workspace-name "$(logAnalyticsWorkspaceName)"
                --network-security-group-name "$(networkSecurityGroupName)"
                --resource-group-name "$(resourceGroupName)"
                --storage-account-name "$(storageAccountName)"
                --virtual-network-name "$(virtualNetworkName)"
